### ISSUE TITLE
exception handling_connection error not working

### ISSUE THREAD

**Issue by deepika171992** [AmadeusITGroup/JumpSSH#126]
Hi,

I am trying to SSH into number of device through loop but when any exception is occuring the code stops there without parsing any further. 
Below is the code :
for ip in ips:
        try:
        	net_connect = gateway_session.get_remote_session(ip,password=passw)
        except ConnectionError as e:
                continue
        else:
                output = net_connect.get_cmd_output('show running-config | i version')
                ver = output.partition('\n')[0]
                results = ip + "," + ver
                to_doc_a(file_name, results)

Error 

Secsh channel 1 open FAILED: Network is unreachable: Connect failed
Traceback (most recent call last):
 ssh_channel = self.proxy_transport.open_channel("direct-tcpip", dest_addr, local_addr)
raise e
paramiko.ssh_exception.ChannelException: ChannelException(2, 'Connect failed')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
net_connect = gateway_session.get_remote_session(ip,password=passw)
remote_session = SSHSession(host=host,
raise exception.ConnectionError("Unable to connect to '%s:%s' with user '%s'"
jumpssh.exception.ConnectionError: Unable to connect to '10.164.8.173:22' with user 'xxxxx': ChannelException(2, 'Connect failed')

**Comment by t-cas** [comment]
Hello @deepika171992,

If the issue is only between gateway and remote host, catching the proper exception should be enough to continue working on other hosts.
If the issue comes from the connection between you localhost and the gateway, it's expected to have all next remote connections failing.

So, not sure what is really your issue here, and for next time, try to put code sample and stack trace with proper formatting so it can be read easily.
