### ISSUE TITLE
Get remote session as another user

### ISSUE THREAD

**Issue by kathe-ruiz** [AmadeusITGroup/JumpSSH#49]
I have the following use case:
- Access a central server via ssh
- Change user to the one with permissions to ssh (via sudo su for example)
- SSH to the other server.
The user with permissions to ssh has all the keys. I could copy the keys to every individual user that can access the server, but I would prefer not doing so.
Is there a way to use get_remote_session with another user? An easy way to run su or sudo su

**Comment by t-cas** [comment]
Hi @kathe-ruiz ,

first, sorry for the late reply
Then , when you use `get_remote_session`, you can specify another user but all credentials (password, key, ...) must be provided and present on your local machine and this is the expected behavior.

So for your use case, the initial user must have all the credentials needed to access all servers until the destination server on his local machine where script is run.

I am not sure if there are ways to workaround this behavior but I didn't find any, feel free to share if you find one :-)
